### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by wangying3426** [fanchou/flutter_escpos#1]
你们是哪个产品在用 flutter ？为啥用 flutter 来做打印功能呢？

**Comment by fanchou** [comment]
> 你们是哪个产品在用 flutter ？为啥用 flutter 来做打印功能呢？

我们主要是收银系统在用打印的，因为我们需要支持各个端(Android、ios、Windows、Mac)，所以我们用的flutter开发的，所以需要用flutter来做打印的。

**Comment by fanchou** [comment]
> 你们是哪个产品在用 flutter ？为啥用 flutter 来做打印功能呢？

我们主要是收银是系统在用打印的，因为我们需要支持各个端(Android、ios、Windows、Mac)，所以我们用的flutter开发的，所以需要用flutter来做打印的。
