### ISSUE TITLE
请教：TSC标签打印机，通过TSPL指令打印不了中文？

### ISSUE THREAD

**Issue by 369663841** [fanchou/flutter_escpos#3]
您好！ 调试发现其它的内容都没问题，就是中文打印不出来， 请问大神如何解决这个问题？ 感谢！

**Comment by fanchou** [comment]
暂时好像没有遇到过，是打印不出来，还是乱码？可能跟打印机的字体有关，用原始的指令能打印中文吗？

**Comment by 369663841** [comment]
感谢回复！ 是打印不出来，非乱码（中文位置空白，其它内容正常），是 TSC的标签打印机，是否因为其不带中文字库呢？

**Comment by fanchou** [comment]
也是有可能的，是有些打印机是不带中文字体的。可以用专门的工具设置的，可以网上找找，试试看。

**Comment by 369663841** [comment]
感谢您提醒！找了个工具 Diagnostic Tool 设了就可以了。 但这种方式也有制约，意味着各打印机都要进行设置。 我在想，通过将 Text 转为 位图，然后用 BITMAP 指令 来输出，然而这种方式打出来是乱码。应该是某些地方处理有问题，我是刚接触 Flutter，请问大神有没有 BITMAP 指令的例子指导一下？ 感谢！
